version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers
      - image: selenium/standalone-chrome-debug:3.141.59-xenon
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run test for V1
          command: yarn test
          environment:
            FORCE_COLOR: '1'
            HACKATHON_APP_VERSION: 'V1'
      - run:
          name: Generate report for V1
          command: |
            mkdir -p /tmp/allure-report/V1
            allure generate allure-results -o "/tmp/allure-report/V1"
      - run:
          name: Run test for V2
          command: yarn test
          environment:
            FORCE_COLOR: '1'
            HACKATHON_APP_VERSION: 'V2'
      - run:
          name: Generate report for V2
          command: |
            mkdir -p /tmp/allure-report/V2
            allure generate allure-results -o "/tmp/allure-report/V2"
      - store_artifacts:
          path: /tmp/allure-report
          prefix: allure-report
